server:
  run-mode: debug  # Set the server to run in debug mode
  http-port:  :8000  # Server port - format as -ip:port (binds to a specific IP) or :port (binds to all IPs)
  read-timeout: 60  # Maximum time (in seconds) to wait for a read operation to complete
  write-timeout: 60  # Maximum time (in seconds) to wait for a write operation to complete
  private-http-listen:  :8001  # Performance monitoring interface (private HTTP server)

security:
  auth-token: 6666  # Token for authenticating image upload API requests
  encryption_key: X-Auth-Token  # Key for encrypting authentication data

log:
  level: debug  # Set the logging level (debug, info, warn, error)
  file:  # Path to the log file (optional field, not specified here)
  production: false  # Whether the application is running in production mode

app:
  default-page-size: 10  # Default number of items per page for pagination
  max-page-size: 100  # Maximum number of items allowed per page for pagination
  default-context-timeout: 60  # Default timeout (in seconds) for the app's operations

  temp-path: storage/temp  # Path for storing temporary files
  upload-url-pre: http://192.168.215.2:9000  # URL prefix for uploaded files
  upload-max-size: 5  # Maximum allowed file size for uploads (in MB)
  upload-allow-exts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif
    - .tiff
    - .avif
    - .webp  # Allowed image file extensions for uploads
  image-max-size-width: 800  # Maximum allowed image width for uploads
  image-max-size-height: 800  # Maximum allowed image height for uploads
  image-quality: 100  # Quality of uploaded images (range: 0-100)

# Local file storage configuration
local-fs:
  is-enable: false  # Whether local file storage is enabled
  httpfs-is-enable: false  # Whether to enable built-in HTTP file access service
  save-path: storage/uploads  # Path to save uploaded files

# Aliyun OSS (Object Storage Service) configuration
oss:
  is-enable: false  # Whether Aliyun OSS cloud storage is enabled
  endpoint:  # Endpoint for the Aliyun OSS service (must be configured)
  bucket-name:  # Name of the OSS bucket (must be configured)
  access-key-id:  # Access key ID for OSS (must be configured)
  access-key-secret:  # Access key secret for OSS (must be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# CloudFlu R2 storage configuration
cloudflu-r2:
  is-enable: false  # Whether R2 cloud storage is enabled
  bucket-name: image  # Name of the R2 bucket
  account-id:  # R2 account ID (must be configured)
  access-key-id:  # R2 access key ID (must be configured)
  access-key-secret:  # R2 access key secret (must be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# AWS S3 storage configuration
aws-s3:
  is-enable: false  # Whether AWS S3 cloud storage is enabled
  region: ap-southeast-1  # AWS region (region code)
  bucket-name:  # Name of the S3 bucket (must be configured)
  access-key-id:  # Access key ID for AWS S3 (must be configured)
  access-key-secret:  # Access key secret for AWS S3 (must be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# MinIO storage configuration
minio:
  is-enable: true  # Whether MinIO storage is enabled
  endpoint: http://192.168.215.2:9000  # MinIO server endpoint URL
  region: test  # MinIO region (can be customized)
  bucket-name: image  # Name of the MinIO bucket
  access-key-id: minioadmin  # MinIO access key ID (default)
  access-key-secret: minioadmin  # MinIO access key secret (default)
  custom-path: blog  # Custom path or prefix for uploaded files

# Email configuration for error reporting
email:
  error-report-enable: false  # Whether to enable error reporting via email
  host: smtp.gmail.com  # SMTP server host for sending emails (Gmail in this case)
  port: 465  # SMTP server port (465 is for SSL connections)
  user-name: xxx  # Email account username for authentication
  password: xxx  # Email account password for authentication
  is-ssl: true  # Whether to use SSL for secure email transmission
  from: xxx  # Sender's email address
  to:
    - xxx  # Recipient(s) email address(es)
