server:
  run-mode: debug  # Set the server run mode to debug (debugging mode)
  http-port:  :8000  # Server port - format: -ip:port (bind to a specific IP) or :port (bind to all IPs)
  read-timeout: 60  # Read timeout (seconds), maximum time to wait before the request times out
  write-timeout: 60  # Write timeout (seconds), maximum time to wait before the write operation times out
  private-http-listen:  :8001  # Performance monitoring interface (private HTTP server)

app:
  default-page-size: 10  # Default number of items per page (pagination)
  max-page-size: 100  # Maximum allowed number of items per page (pagination)
  default-context-timeout: 60  # Default timeout (seconds) for application operations

  temp-path: storage/temp  # Path for storing temporary files
  upload-url-pre: http://192.168.215.2:9000  # URL prefix for file uploads
  upload-max-size: 5  # Maximum size for file uploads (MB)
  upload-allow-exts:
    - .jpg
    - .jpeg
    - .png
    - .bmp
    - .gif
    - .tiff
    - .avif
    - .webp  # Allowed image file extensions for upload
  image-max-size-width: 800  # Maximum width for uploaded images
  image-max-size-height: 800  # Maximum height for uploaded images
  image-quality: 100  # Image quality for uploads (range: 0-100)

log:
  level: Debug  # Log level
  file: storage/logs/log.log # Log file path
  production: true  # Whether this is a production environment

security:
  auth-token: 6666  # Authorization Token for image upload API
  encryption_key: X-Auth-Token  # Key for encrypting authentication data

database:
  type: sqlite
  path: storage/database/db.db
  table-prefix: pre_
  auto-migrate: true

user:
  is-enable: false  # Whether the public user interface is enabled
  register-is-enable: false  # Whether the public user interface allows registration

# Local file storage configuration
local-fs:
  is-enable: false  # Whether to enable local file storage
  httpfs-is-enable: false  # Whether to enable the built-in HTTP file access service
  save-path: storage/uploads  # Path for saving uploaded files

# Alibaba Cloud OSS configuration
oss:
  is-enable: false  # Whether to enable Alibaba Cloud OSS storage
  endpoint:  # OSS service endpoint (needs to be configured)
  bucket-name:  # OSS bucket name (needs to be configured)
  access-key-id:  # OSS access key ID (needs to be configured)
  access-key-secret:  # OSS access key secret (needs to be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# CloudFlu R2 storage configuration
cloudflu-r2:
  is-enable: false  # Whether to enable R2 cloud storage
  bucket-name: image  # R2 bucket name
  account-id:  # R2 account ID (needs to be configured)
  access-key-id:  # R2 access key ID (needs to be configured)
  access-key-secret:  # R2 access key secret (needs to be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# AWS S3 storage configuration
aws-s3:
  is-enable: false  # Whether to enable AWS S3 cloud storage
  region: ap-southeast-1  # AWS region (region code)
  bucket-name:  # S3 bucket name (needs to be configured)
  access-key-id:  # S3 access key ID (needs to be configured)
  access-key-secret:  # S3 access key secret (needs to be configured)
  custom-path: blog  # Custom path or prefix for uploaded files

# MinIO storage configuration
minio:
  is-enable: true  # Whether to enable MinIO storage
  endpoint: http://192.168.215.2:9000  # MinIO server endpoint URL
  region: test  # MinIO region (can be customized)
  bucket-name: image  # MinIO bucket name
  access-key-id: minioadmin  # MinIO access key ID (default value)
  access-key-secret: minioadmin  # MinIO access key secret (default value)
  custom-path: blog  # Custom path or prefix for uploaded files

# Email configuration (for error reporting)
email:
  error-report-enable: false  # Whether to enable sending error reports via email
  host: smtp.gmail.com  # Email sending server host (here, Gmail)
  port: 465  # Email server port (465 is the port for SSL connection)
  user-name: xxx  # Username for the email account (for authentication)
  password: xxx  # Password for the email account (for authentication)
  is-ssl: true  # Whether to use SSL secure protocol for email transmission
  from: xxx  # Sender's email address
  to:
    - xxx  # Recipient's email address
