package code

var (
	Failed        = NewError(0, lang{zh: "失败", en: "Failed"})
	Success       = NewSuss(1, lang{zh: "成功", en: "Success"})
	SuccessCreate = NewSuss(2, lang{zh: "创建成功", en: "Create Success"})
	SuccessUpdate = NewSuss(3, lang{zh: "更新成功", en: "Update Success"})
	SuccessDelete = NewSuss(4, lang{zh: "删除成功", en: "Delete Success"})

	ErrorServerInternal               = NewError(incr(500), lang{zh: "服务器内部错误", en: "Server Internal Error"})
	ErrorNotFoundAPI                  = NewError(incr(400), lang{zh: "找不到API", en: "Not Found API"})
	ErrorInvalidParams                = NewError(incr(400), lang{zh: "参数验证失败", en: "Invalid Params"})
	ErrorTooManyRequests              = NewError(incr(400), lang{zh: "请求过多", en: "Too Many Requests"})
	ErrorInvalidAuthToken             = NewError(incr(400), lang{zh: "访问令牌效验失败", en: "Invalid Auth Token"})
	ErrorNotUserAuthToken             = NewError(incr(400), lang{zh: "尚未登录,请先登录", en: "Not logged in. Please log in first."})
	ErrorInvalidUserAuthToken         = NewError(incr(400), lang{zh: "登录状态失效,请重新登录", en: "Session expired, please log in again."})
	ErrorInvalidToken                 = NewError(incr(400), lang{zh: "您的访问缺少用户令牌", en: "Your access is missing a user token"})
	ErrorTokenExpired                 = NewError(incr(400), lang{zh: "用户令牌已过期", en: "User token has expired"})
	ErrorUserRegister                 = NewError(incr(400), lang{zh: "用户注册失败", en: "User registration failed"})
	ErrorPasswordNotValid             = NewError(incr(400), lang{zh: "密码不符合规则", en: "Password does not meet the rules"})
	ErrorUserLoginPasswordFailed      = NewError(incr(400), lang{zh: "密码错误", en: "Password error"})
	ErrorUserRegisterIsDisable        = NewError(incr(400), lang{zh: "用户注册已关闭", en: "User registration is closed"})
	ErrorUserLoginFailed              = NewError(incr(400), lang{zh: "用户登录失败", en: "User login failed"})
	ErrorUserNotFound                 = NewError(incr(400), lang{zh: "用户不存在", en: "User does not exist"})
	ErrorUserEmailAlreadyExists       = NewError(incr(400), lang{zh: "用户邮箱已存在", en: "User email already exists"})
	ErrorUserUsernameNotValid         = NewError(incr(400), lang{zh: "用户名不符合规则,用户名长度为3-15位,只能包含字母、数字或下划线", en: "The username does not meet the rules, the username length is 3-15 digits, and can only contain letters, numbers or underscores"})
	ErrorUserPasswordNotMatch         = NewError(incr(400), lang{zh: "两次输入的密码不一致", en: "The two passwords entered are inconsistent"})
	ErrorDBQuery                      = NewError(incr(400), lang{zh: "数据库查询失败", en: "Database query failed"})
	ErrorUploadFileFailed             = NewError(incr(400), lang{zh: "上传文件失败", en: "Upload file failed"})
	ErrorInvalidCloudStorageType      = NewError(incr(400), lang{zh: "云存储类型无效", en: "Invalid cloud storage type"})
	ErrorInvalidStorageType           = NewError(incr(400), lang{zh: "存储类型无效", en: "Invalid storage type"})
	ErrorInvalidCloudStorageAccountId = NewError(incr(400), lang{zh: "云存储账户ID无效", en: "Invalid cloud storage account ID"})
	ErrorInvalidCloudStorageRegion    = NewError(incr(400), lang{zh: "云存储区域无效", en: "Invalid cloud storage region"})
	ErrorInvalidCloudStorageEndpoint  = NewError(incr(400), lang{zh: "云存储端点无效", en: "Invalid cloud storage endpoint"})
)
